# -*- coding: utf-8 -*-
"""Radar Nantes 1.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM595vprYPMefPbcLVOrOukJ9beux5U6
"""

import streamlit as st
import pandas as pd
import folium
from folium.plugins import LocateControl
from streamlit_folium import st_folium
import requests
from datetime import datetime
from streamlit_js_eval import get_geolocation
import math

# --- CONFIGURATION (Secrets Streamlit) ---
UBER_TOKEN = st.secrets.get("UBER_TOKEN", "h9A73ihoqHbvhOTurEmknI578lE0oJ3_Oa9Xlrf4")
TELEGRAM_TOKEN = st.secrets.get("TELEGRAM_TOKEN", "TON_TOKEN_BOT")
CHAT_ID = st.secrets.get("CHAT_ID", "TON_CHAT_ID")

# Liste des SITES mise à jour avec Aéroport et Hangar
SITES = {
    "Commerce": [47.213, -1.558],
    "Gare": [47.217, -1.542],
    "Ile de Nantes": [47.206, -1.553],
    "Atlantis": [47.223, -1.637],
    "Route de Vannes": [47.234, -1.603],
    "Rezé": [47.191, -1.571],
    "Beaujoire": [47.255, -1.524],
    "Pirmil": [47.199, -1.542],
    "Aéroport": [47.156, -1.607],
    "Hangar à Bananes": [47.200, -1.572]
}

# --- CALCUL DE DISTANCE ---
def get_distance(pos1, pos2):
    R = 6371 
    lat1, lon1 = math.radians(pos1[0]), math.radians(pos1[1])
    lat2, lon2 = math.radians(pos2[0]), math.radians(pos2[1])
    dlat, dlon = lat2 - lat1, lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    return R * (2 * math.atan2(math.sqrt(a), math.sqrt(1-a)))

# --- FONCTION TELEGRAM ---
def send_telegram(message):
    if TELEGRAM_TOKEN and CHAT_ID:
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        try:
            requests.post(url, data={"chat_id": CHAT_ID, "text": message}, timeout=5)
        except: pass

# --- MOTEUR API UBER ---
def get_surge_real(lat, lng):
    destinations = [{"lat": lat + 0.018, "lng": lng}, {"lat": lat - 0.018, "lng": lng}]
    surges = []
    headers = {'Authorization': f'Token {UBER_TOKEN}', 'Accept-Language': 'fr_FR'}
    for dest in destinations:
        url = (f"https://api.uber.com/v1.2/estimates/price?"
               f"start_latitude={lat}&start_longitude={lng}&"
               f"end_latitude={dest['lat']}&end_longitude={dest['lng']}")
        try:
            r = requests.get(url, headers=headers, timeout=10)
            data = r.json()
            if 'prices' in data:
                for p in data['prices']:
                    if p['display_name'] == 'UberX':
                        surges.append(p.get('surge_multiplier', 1.0))
        except: continue
    return sum(surges) / len(surges) if surges else 1.0

# --- INTERFACE ---
st.set_page_config(page_title="Radar Pro Nantes", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;} header {visibility: hidden;} footer {visibility: hidden;}
    .leaflet-control-attribution {display: none !important;}
    .block-container { padding: 0.5rem 1rem 0rem 1rem !important; }
    .stButton>button { width: 100%; border-radius: 8px; height: 3.5em; background-color: #007bff; color: white; font-weight: bold; }
    </style>
    """, unsafe_allow_html=True)

# 1. ACTIONS
cols = st.columns([4, 1])
with cols[0]:
    do_scan = st.button("🚀 SCAN PROXIMITÉ (5KM)")
with cols[1]:
    prediction_mode = st.toggle("🔮", value=False)

# 2. GÉOLOCALISATION
loc = get_geolocation()
my_pos = [loc['coords']['latitude'], loc['coords']['longitude']] if loc and 'coords' in loc else [47.218, -1.553]

# 3. CARTE
m = folium.Map(location=my_pos, zoom_start=13, tiles="CartoDB dark_matter", zoom_control=False)
LocateControl(auto_start=False, flyTo=True, keepCurrentZoomLevel=True).add_to(m)

# Cercle de zone d'action (5km) en bleu clair
folium.Circle(location=my_pos, radius=5000, color="#3388ff", weight=2, fill=False, dash_array='5, 10').add_to(m)

bonus_pred = 0.2 if (prediction_mode and 18 <= datetime.now().hour <= 21) else 0

for name, coords in SITES.items():
    dist = get_distance(my_pos, coords)
    surge_api = get_surge_real(coords[0], coords[1])
    final_surge = surge_api + bonus_pred
    
    # Notification Telegram si dans le périmètre (5km) et surge >= 1.2
    if do_scan and dist <= 5.0 and final_surge >= 1.2:
        send_telegram(f"🔔 ZONE PROCHE ({dist:.1f}km)\n🔥 {name}: x{final_surge:.2f}")

    color = "red" if final_surge >= 1.4 else "orange" if final_surge >= 1.2 else "green"
    folium.CircleMarker(location=coords, radius=min(final_surge*22, 65), color=color, fill=True, fill_opacity=0.4).add_to(m)
    folium.Marker(
        location=coords, 
        icon=folium.DivIcon(
            html=f'<div style="font-size: 11pt; color: white; font-weight: bold; text-shadow: 2px 2px #000; width:60px;">x{final_surge:.2f}</div>', 
            icon_anchor=(15, 7)
        )
    ).add_to(m)

st_folium(m, width="100%", height=580, returned_objects=[])
st.caption(f"Radar Nantes | {datetime.now().strftime('%H:%M')}")
