# -*- coding: utf-8 -*-
"""Radar Nantes 1.5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM595vprYPMefPbcLVOrOukJ9beux5U6
"""

import streamlit as st
import pandas as pd
import folium
from folium.plugins import LocateControl
from streamlit_folium import st_folium
import requests
from datetime import datetime
from streamlit_js_eval import get_geolocation

# --- CONFIGURATION ---
UBER_TOKEN = st.secrets.get("UBER_TOKEN", "h9A73ihoqHbvhOTurEmknI578lE0oJ3_Oa9Xlrf4")

SITES = {
    "Commerce": [47.213, -1.558],
    "Gare": [47.217, -1.542],
    "Ile de Nantes": [47.206, -1.553],
    "Atlantis": [47.223, -1.637],
    "Route de Vannes": [47.234, -1.603],
    "Rezé": [47.191, -1.571],
    "Beaujoire": [47.255, -1.524],
    "Pirmil": [47.199, -1.542]
}

# --- MOTEUR API ---
def get_surge_real(lat, lng):
    destinations = [{"lat": lat + 0.018, "lng": lng}, {"lat": lat - 0.018, "lng": lng}]
    surges = []
    headers = {'Authorization': f'Token {UBER_TOKEN}', 'Accept-Language': 'fr_FR'}
    for dest in destinations:
        url = (f"https://api.uber.com/v1.2/estimates/price?"
               f"start_latitude={lat}&start_longitude={lng}&"
               f"end_latitude={dest['lat']}&end_longitude={dest['lng']}")
        try:
            r = requests.get(url, headers=headers, timeout=10)
            data = r.json()
            if 'prices' in data:
                for p in data['prices']:
                    if p['display_name'] == 'UberX':
                        surges.append(p.get('surge_multiplier', 1.0))
        except: continue
    return sum(surges) / len(surges) if surges else 1.0

# --- INTERFACE MOBILE ---
st.set_page_config(page_title="Radar Pro", layout="wide", initial_sidebar_state="collapsed")

# CSS Nettoyage (Barre GitHub cachée)
st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    header {visibility: hidden;}
    footer {visibility: hidden;}
    .block-container { padding: 0.5rem 1rem 0rem 1rem !important; }
    .stButton>button { width: 100%; border-radius: 8px; height: 3.5em; background-color: #007bff; color: white; font-weight: bold; }
    /* Style pour les étiquettes de surge sur la carte */
    .leaflet-tooltip { background: rgba(0,0,0,0.7); color: white; border: none; font-weight: bold; font-size: 12px; }
    </style>
    """, unsafe_allow_html=True)

# 1. ACTIONS
cols = st.columns([4, 1])
with cols[0]:
    if st.button("🚀 SCAN NANTES"):
        st.rerun()
with cols[1]:
    prediction_mode = st.toggle("🔮", value=False)

# 2. CARTE (Centrée par défaut sur Nantes)
m = folium.Map(location=[47.218, -1.553], zoom_start=13, tiles="CartoDB dark_matter", zoom_control=False)

# BOUTON DE RECENTRAGE (Gère ton point bleu tout seul)
LocateControl(
    auto_start=False, 
    flyTo=True, 
    keepCurrentZoomLevel=True,
    strings={"title": "Ma position"}
).add_to(m)

bonus_pred = 0.2 if (prediction_mode and 18 <= datetime.now().hour <= 21) else 0

# 3. BOUCLE DES SITES AVEC SURGE EXACT
for name, coords in SITES.items():
    surge_api = get_surge_real(coords[0], coords[1])
    final_surge = surge_api + bonus_pred
    
    color = "red" if final_surge >= 1.4 else "orange" if final_surge >= 1.2 else "green"
    radius_val = min(final_surge * 22, 65)
    
    # Le cercle
    folium.CircleMarker(
        location=coords,
        radius=radius_val,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.4,
    ).add_to(m)

    # L'ÉTIQUETTE (S'affiche en permanence au centre du cercle)
    folium.Marker(
        location=coords,
        icon=folium.DivIcon(
            html=f'<div style="font-size: 10pt; color: white; font-weight: bold; text-shadow: 1px 1px #000; width: 50px;">x{final_surge:.2f}</div>',
            icon_anchor=(15, 7)
        )
    ).add_to(m)

st_folium(m, width="100%", height=580, returned_objects=[])
st.caption(f"MàJ: {datetime.now().strftime('%H:%M:%S')}")
