# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/nabnb13-art/04b0945e8bbecdbd2171281e403d859f/untitled1.ipynb
"""

!pip install streamlit folium streamlit-folium
import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
import requests
from datetime import datetime

# --- CONFIGURATION (Identique à ton script précédent) ---
UBER_TOKEN = "HtMY2g6iUkf-TQPBY75KccPOUz0j7Bp9e-uEERbg"

SITES = {
    "Commerce": [47.213, -1.558],
    "Gare": [47.217, -1.542],
    "Ile de Nantes": [47.206, -1.553],
    "Atlantis": [47.223, -1.637],
    "Route de Vannes": [47.234, -1.603],
    "Rezé": [47.191, -1.571],
    "Beaujoire": [47.255, -1.524],
    "Pirmil": [47.199, -1.542]
}

def get_color(surge):
    if surge >= 1.4: return "red"
    if surge >= 1.2: return "orange"
    return "green"

st.set_page_config(page_title="Radar Uber Nantes", layout="wide")
st.title("🚀 Radar de Demande - Nantes")

# Bouton de rafraîchissement manuel
if st.button('Actualiser la carte'):
    st.rerun()

# Création de la carte centrée sur Nantes
m = folium.Map(location=[47.218, -1.553], zoom_start=13, tiles="cartodbpositron")

# Scan des zones et ajout sur la carte
for name, coords in SITES.items():
    # Ici on appelle ta fonction get_surge habituelle (simplifiée pour l'exemple)
    # surge = get_surge(name, coords[0], coords[1])
    surge = 1.0 # Remplacer par l'appel API réel

    color = get_color(surge)

    folium.CircleMarker(
        location=coords,
        radius=20,
        popup=f"{name}: x{surge}",
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.6
    ).add_to(m)

# Affichage de la carte dans l'app
st_folium(m, width=700, height=500)

st.caption(f"Dernière mise à jour : {datetime.now().strftime('%H:%M:%S')}")